// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_little_knowledge = "CgkIhJSNl6ILEAIQDg"; // <GPGSID>
        public const string achievement_smart = "CgkIhJSNl6ILEAIQCw"; // <GPGSID>
        public const string achievement_brilliant = "CgkIhJSNl6ILEAIQDA"; // <GPGSID>
        public const string achievement_medium_point = "CgkIhJSNl6ILEAIQBg"; // <GPGSID>
        public const string achievement_pro_runner = "CgkIhJSNl6ILEAIQBQ"; // <GPGSID>
        public const string achievement_first_step = "CgkIhJSNl6ILEAIQCA"; // <GPGSID>
        public const string achievement_congratulations = "CgkIhJSNl6ILEAIQCg"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIhJSNl6ILEAIQAQ"; // <GPGSID>
        public const string achievement_medium_knowledge = "CgkIhJSNl6ILEAIQDw"; // <GPGSID>
        public const string achievement_intermediate_runner = "CgkIhJSNl6ILEAIQBA"; // <GPGSID>
        public const string achievement_halfway_there = "CgkIhJSNl6ILEAIQCQ"; // <GPGSID>
        public const string achievement_small_point = "CgkIhJSNl6ILEAIQAw"; // <GPGSID>
        public const string achievement_genius = "CgkIhJSNl6ILEAIQDQ"; // <GPGSID>
        public const string achievement_newbie_runner = "CgkIhJSNl6ILEAIQAA"; // <GPGSID>
        public const string achievement_big_point = "CgkIhJSNl6ILEAIQBw"; // <GPGSID>
        public const string achievement_big_knowledge = "CgkIhJSNl6ILEAIQEA"; // <GPGSID>

}

